### ISSUE TITLE
Escape Rope durability reset

### ISSUE THREAD

**Issue by ChromaPIE** [Luligabi1/MiningUtility#6]
I thought the escape rope sends players straight above to the nearest spot that exposed to the sky, but well, though being an extremely cheap global teleporting tool already made it overpowered, if it was designed to be like this I won't refuse.

The problem is, it's not one use only, it has 16 whole points of durability, all that costing only four strings and 1 iron nugget. But that's not the worst thing —— When you perform a coordinate rebind the durability got reset to its full, making it in fact unbreakable.

So my suggestion is, fix the bug at least. Including smth like Ender Pearl in its recipe, or lower its durability would make it even better.

**Comment by Luligabi1** [comment]
Thanks for the report - I'll look into the possibilities after the bug is fixed, currently I'm thinking of making it either single use (configurable) or having a single use escape rope + a advanced escape rope similar to what we have now, also configurable

**Comment by Luligabi1** [comment]
I'm putting off the changes until 1.21 comes around so there won't be any issues with existing escape ropes - the proposed changes can be now tracked at #7 . As for the bug, it's been fixed on `1.2.7+1.20.1`, it'll be available soon on CF and Modrinth. Thanks for reporting!
