### ISSUE TITLE
1.21 Texture Opacity

### ISSUE THREAD

**Issue by makumaku1974** [Luligabi1/MiningUtility#9]
![image](https://github.com/user-attachments/assets/c06ff862-100b-4fc1-9db2-749888921fbd)

**Comment by makumaku1974** [comment]
![image](https://github.com/user-attachments/assets/4bc78d1c-1401-4243-bec6-84c0bb017057)

**Comment by Luligabi1** [comment]
Fixed on `2.0.1+1.21`, thanks for reporting!
